### ISSUE TITLE
Change properties of Apostille to protected from private

### ISSUE THREAD

**Issue by jontey** [luxtagofficial/Apostille-library#11]
We are having issues with accessing private variables from `Apostille` class when we extend the class. 

Suggest changing `private` properties to `protected` to enable child classes to access the variables. 

http://www.typescriptlang.org/docs/handbook/classes.html#understanding-protected

**Comment by gimyboya** [comment]
you mean all private properties or few?

**Comment by jontey** [comment]
This one in particular 

```js
[line 32]
private transactions: IReadyTransaction[] = [];
```

**Comment by gimyboya** [comment]
It's highly not likely that you want to access the transactions as they are chronologically created and should not be tampered with, however for test purposes you can do this trick:
```
// tslint:disable-next-line:no-string-literal
expect(privateApostille['transactions'][0].type).toEqual(TransactionType.TRANSFER);
```
