### ISSUE TITLE
Tests fail

### ISSUE THREAD

**Issue by dgarcia360** [luxtagofficial/Apostille-library#16]
**Describe the bug**

Tests are failing.

Test Suites: 8 failed, 4 passed, 12 total

* NEM-SDK can't be imported correctly since is not typescript compatible. It fails when doing nem.model, nem.utils ...[Example](tests/unit/Private/Hashs.spec.ts. )
* Variables are used but never read. [Example](https://github.com/luxtagofficial/Apostille-library/blob/master/tests/unit/Private/Functionalities.spec.ts#L137)
* Possible undefined objects are not treated. Check first if the transaction has property transactionInfo. [Example](https://github.com/luxtagofficial/Apostille-library/blob/master/tests/unit/ApostilleAccount.spec.ts#L77)

**To Reproduce**

``clone the repo``
``npm install``
``npm test``

**Environment**
 - OS: Windows 10

**Comment by gimyboya** [comment]
what typescript version are you using?

**Comment by gimyboya** [comment]
This is weird. the tests are running fin with our internal team maybe @jontey or @wzulfikar could assist on this?

**Comment by dgarcia360** [comment]
Tried on Mac and got the same errors:

Test Suites: 8 failed, 4 passed, 12 total

**Comment by jontey** [comment]
I have the same errors. Will investigate further

**Comment by gimyboya** [comment]
@dgarcia360 please checkout to the latest develop @jontey has merged #18 if everything is working well will merge it to master.

**Comment by dgarcia360** [comment]
Thanks!  The errors spotted are fixed. 

 I still get some errors while running the tests due to :

    Timeout - Async callback was not invoked within the 5000ms timeout specified by jest.setTimeout.

**Comment by jontey** [comment]
@dgarcia360 it might be because the catapult testnet is not responding. See if you can view http://api.beta.catapult.mijin.io:3000 and try to run the tests again.

**Comment by gimyboya** [comment]
yes that's an error that happens when there is a connection problem. the test should pass if the connection is fine you can try increase the timeout in the test files. @dgarcia360 

I am closing this issue

**Comment by dgarcia360** [comment]
Yes, it worked increasing the timeout to 20s.

Thanks!
