### ISSUE TITLE
Remove network type from Apostille class constructor parameter

### ISSUE THREAD

**Issue by aizaiz** [luxtagofficial/Apostille-library#3]
@gimyboya  Apostille class can get Network type from account parameter.

it's to reduce redundancy and can remove some code validation like this
```
   if (generatorAccount.address.networkType !== networkType) {
      throw new Error('network type miss matched!');
    }
```

**Comment by gimyboya** [comment]
this will break a lot of code knowing that it will affect the constructor, however, I think it's still relevant to fix this
