### ISSUE TITLE
getCosignatories should return `Promise<PublicAccount[]>` instead of `Promise<object[]>`

### ISSUE THREAD

**Issue by jontey** [luxtagofficial/Apostille-library#5]
getCosignatories should return `Promise<PublicAccount[]>` instead of `Promise<object[]>`. See https://github.com/nemtech/nem2-sdk-typescript-javascript/blob/master/src/model/account/MultisigAccountInfo.ts `line 46`

```
public getCosignatories(urls: string): Promise<object[]> {
...
```

Source: https://github.com/luxtagofficial/Apostille-library/blob/master/src/ApostilleAccount.ts

**Comment by gimyboya** [comment]
@aizaiz can you please look into this?
